apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apache-virtualservice
spec:
  hosts:
  - apache.default.158.178.230.133.nip.io
  gateways:
  - apache-gateway
  http:
    - route:
      - destination:
        host: apache-service
        port:
          number: 80